config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "/about", to: "about#index"
  get "/contact", to: "contact#index"
  resources :projects, only: [ :index, :show ]
  post "/contact", to: "contact#create"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :blog, only: [ :index, :show ], controller: "blog", param: :slug

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  def admin_routes
    devise_for :admins, controllers: { sessions: "admins/sessions" }, path: "admin_auth"
    namespace :admin_panel do
      root to: "dashboard#index"
      resources :blog_posts, param: :slug do
        member do
          patch :toggle_publish
          patch :toggle_hidden
        end
      end
      resources :tags, only: [ :new, :create ]
    end
  end

  if Rails.env.test?
    admin_routes
  end

  if Rails.env.development? || Rails.env.production?
    constraints lambda { |req|
      Rails.configuration.admin_allowed_ips.any? { |ip| req.remote_ip.start_with?(ip) }
    } do
      admin_routes
    end
  end
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  before_validation :generate_slug, if: :title_changed?
  before_save :set_published_at, if: :published?
  after_commit :refresh_sitemap, on: [ :create, :update, :destroy ]

  before_update :prevent_slug_change_if_published

  validates :title, presence: true
  validates :content, presence: true
  validates :slug, uniqueness: true, presence: true

  has_many :blog_post_tags, dependent: :destroy
  has_many :tags, through: :blog_post_tags

  scope :published, -> { where(published: true).where("published_at <= ?", Time.current) }
  scope :visible, -> { where(hidden: false) }
  scope :by_tag, ->(tag_name) { joins(:tags).where(tags: { name: tag_name }) }

  def to_param
    slug
  end

  private

  def refresh_sitemap
    SitemapRefreshJob.perform_later
  end

  def generate_slug
    self.slug = title.parameterize if slug.blank?
  end

  def prevent_slug_change_if_published
    if published? && slug_changed?
      errors.add(:slug, "cannot be changed after publishing.")
      throw(:abort)
    end
  end

  def set_published_at
    self.published_at ||= Time.current if published?
  end
end

app/controllers/admin_panel/blog_posts_controller.rb
module AdminPanel
  class BlogPostsController < ApplicationController
    before_action :authenticate_admin

    before_action :disable_turbo, only: [ :new, :edit, :create, :update ]

    def index
      @blog_posts = BlogPost.order(published_at: :desc)
    end

    def new
      @blog_post = BlogPost.new
    end

    def create
      @blog_post = BlogPost.new(blog_post_params)
      @blog_post.hidden = true
      if @blog_post.save
        redirect_to admin_panel_blog_posts_path, notice: "Blog post created successfully!"
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @blog_post = BlogPost.find_by(slug: params[:slug])
    end

    def update
      @blog_post = BlogPost.find_by(slug: params[:slug])

      if @blog_post.update(blog_post_params)
        redirect_to admin_panel_blog_posts_path, notice: "Blog post updated successfully!"
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @blog_post = BlogPost.find_by(slug: params[:slug])
      if @blog_post.destroy
        redirect_to admin_panel_blog_posts_path, notice: "Blog post deleted successfully!"
      else
        redirect_to admin_panel_blog_posts_path, alert: "Failed to delete blog post."
      end
    end

    def toggle_publish
      @blog_post = BlogPost.find_by(slug: params[:slug])
      @blog_post.update(published: !@blog_post.published)
      redirect_to admin_panel_blog_posts_path
    end

    def toggle_hidden
      @blog_post = BlogPost.find_by(slug: params[:slug])
      @blog_post.update(hidden: !@blog_post.hidden)
      redirect_to admin_panel_blog_posts_path
    end

    private

    def blog_post_params
      params.require(:blog_post).permit(:title, :content, :slug, tag_ids: [])
    end

    def disable_turbo
      response.headers["Turbo-Frame"] = "false"
    end

    def authenticate_admin
      redirect_to new_admin_session_path, alert: "You must be an admin to access this page." unless current_admin
    end
  end
end

app/controllers/admin_panel/dashboard_controller.rb
module AdminPanel
  class DashboardController < ApplicationController
    before_action :authenticate_admin!
    before_action :restrict_to_lan

    def index
      render "admin_panel/dashboard/index"
    end

    private

    def restrict_to_lan
      allowed_ips = Rails.configuration.admin_allowed_ips
      unless allowed_ips.any? { |ip| request.remote_ip.start_with?(ip) }
        render file: Rails.public_path.join("404.html"), status: :not_found, layout: false
      end
    end
  end
end

app/controllers/admin_panel/tags_controller.rb
module AdminPanel
  class TagsController < ApplicationController
    before_action :authenticate_admin!

    def new
      @tag = Tag.new
    end

    def create
      @tag = Tag.new(tag_params)
      if @tag.save
        redirect_to admin_panel_blog_posts_path, notice: "Tag created successfully!"
      else
        render :new, status: :unprocessable_entity
      end
    end

    private

    def tag_params
      params.require(:tag).permit(:name)
    end
  end
end

app/helpers/admin_panel/blog_posts_helper.rb
module AdminPanel::BlogPostsHelper
end

app/helpers/admin_panel/tags_helper.rb
module AdminPanel::TagsHelper
end

app/views/admin_panel/blog_posts/_form.html.erb
<%= form_with(model: @blog_post, url: @blog_post.new_record? ? admin_panel_blog_posts_path : admin_panel_blog_post_path(@blog_post.slug), method: @blog_post.new_record? ? :post : :patch, local: true) do |form| %>

<% if @blog_post.errors.any? %>
<div class="error_messages">
    <ul>
        <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div>
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
</div>

<div data-controller="markdown-editor">
    <%= form.label :content %>
    <%= form.text_area :content, data: { markdown_editor_target: "textarea" }%>
</div>

<div>
    <%= form.label :tags %>
    <%= form.collection_select :tag_ids, Tag.all, :id, :name, { include_blank: false }, multiple: true, class: "tag-select" %>
</div>

<%= form.submit @blog_post.new_record? ? "Create Blog Post" : "Update Blog Post" %>
<% end %>

app/views/admin_panel/blog_posts/create.hmtl.erb
<!-- app/views/admin_panel/blog_posts/create.html.erb -->
<%= turbo_stream.append "blog_posts" do %>
  <%= render @blog_post %>
<% end %>

app/views/admin_panel/blog_posts/edit.html.erb
<%= turbo_frame_tag "content" do %>
  <h1>Edit Blog Post</h1>
  <%= render "form" %> <!-- Render the form partial for editing -->
  <%= link_to "Back to Blog Posts", admin_panel_blog_posts_path, data: { turbo: false } %>
<% end %>

app/views/admin_panel/blog_posts/index.html.erb
<%= turbo_frame_tag "content" do %>
  <h1>Manage Blog Posts</h1>

  <%= link_to "New Blog Post", new_admin_panel_blog_post_path %>

  <table class="table table-bordered mt-3">
    <thead>
      <tr>
        <th>Title</th>
        <th>Created at</th>
        <th>Updated at</th>
        <th>Published</th>
        <th>Hidden</th>
        <th>Tags</th>
        <th colspan="4" class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @blog_posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.created_at.strftime("%Y/%m/%d") %></td>
          <td><%= post.updated_at.strftime("%Y/%m/%d") %></td>
          <td><%= post.published? %></td>
          <td><%= post.hidden? %></td>
          <td>
            <% if post.tags.any? %>
              <span class="tooltip-container">
                <%= post.tags.count %> tags
                <span class="tooltip-text"><%= post.tags.map(&:name).join(', ') %></span>
              </span>
            <% else %>
              No tags
            <% end %>
          </td>
          <td colspan="4" class="text-center">
            <div class="btn-group" role="group">
              <%= link_to "Edit", edit_admin_panel_blog_post_path(post) %> |
              <%= button_to "Delete", admin_panel_blog_post_path(post), method: :delete, data: { confirm: "Are you sure?" } %> |
              <%= button_to "Publish", toggle_publish_admin_panel_blog_post_path(post), method: :patch, disabled: post.published? %> |
              <%= button_to post.hidden? ? "Unhide" : "Hide", toggle_hidden_admin_panel_blog_post_path(post), method: :patch %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admin_panel/blog_posts/new.html.erb
<%= turbo_frame_tag "content" do %>
  <h1>Create New Blog Post</h1>
  <%= render "form" %> <!-- Render the form partial here -->
<% end %>