config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "/about", to: "about#index"
  get "/contact", to: "contact#index"
  resources :projects, only: [ :index, :show ]
  post "/contact", to: "contact#create"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :blog, only: [ :index, :show ], controller: "blog", param: :slug

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  def admin_routes
    devise_for :admins, controllers: { sessions: "admins/sessions" }, path: "admin_auth"
    namespace :admin_panel do
      root to: "dashboard#index"
      resources :blog_posts, param: :slug do
        member do
          patch :toggle_publish
          patch :toggle_hidden
        end
      end
      resources :tags, only: [ :new, :create ]
    end
  end

  if Rails.env.test?
    admin_routes
  end

  if Rails.env.development? || Rails.env.production?
    constraints lambda { |req|
      Rails.configuration.admin_allowed_ips.any? { |ip| req.remote_ip.start_with?(ip) }
    } do
      admin_routes
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  before_validation :generate_slug, if: :title_changed?
  before_save :set_published_at, if: :published?
  after_commit :refresh_sitemap, on: [ :create, :update, :destroy ]

  before_update :prevent_slug_change_if_published

  validates :title, presence: true
  validates :content, presence: true
  validates :slug, uniqueness: true, presence: true

  has_many :blog_post_tags, dependent: :destroy
  has_many :tags, through: :blog_post_tags

  scope :published, -> { where(published: true).where("published_at <= ?", Time.current) }
  scope :visible, -> { where(hidden: false) }
  scope :by_tag, ->(tag_name) { joins(:tags).where(tags: { name: tag_name }) }

  def to_param
    slug
  end

  private

  def refresh_sitemap
    SitemapRefreshJob.perform_later
  end

  def generate_slug
    self.slug = title.parameterize if slug.blank?
  end

  def prevent_slug_change_if_published
    if published? && slug_changed?
      errors.add(:slug, "cannot be changed after publishing.")
      throw(:abort)
    end
  end

  def set_published_at
    self.published_at ||= Time.current if published?
  end
end

app/models/blog_post_tag.rb
class BlogPostTag < ApplicationRecord
  belongs_to :blog_post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :blog_post_tags, dependent: :destroy
  has_many :blog_posts, through: :blog_post_tags

  validates :name, presence: true, uniqueness: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @blog_posts = BlogPost.published.visible.order(published_at: :desc)
    @blog_posts = @blog_posts.by_tag(params[:tag]) if params[:tag]
  end

  def show
    @blog_post = BlogPost.published.visible.find_by!(slug: params[:slug])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def create
    respond_to do |format|
      if send_email
        format.turbo_stream do
          render turbo_stream: turbo_stream.update(
            "contact_form_status",
            partial: "contact/success"
          )
        end
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.update(
            "contact_form_status",
            partial: "contact/error"
          )
        end
      end
    end
  end

  private

  def send_email
    name = contact_params[:name]
    email = contact_params[:email]
    message = contact_params[:message]

    ContactMailer.contact_email(name, email, message).deliver_now
    true
  rescue StandardError => e
    Rails.logger.error "Email failed: #{e.message}"
    false
  end

  def contact_params
    params.permit(:name, :email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
require "ostruct"


class ProjectsController < ApplicationController
  PROJECTS = {
    # "project1" => "Homelab",
    "project2" => "Personal Website"
  }.freeze

  def index
    @projects = PROJECTS.map do |id, name|
      OpenStruct.new(id: id, name: name)
    end
  end

  def show
    project_id = params[:id]

    if PROJECTS.key?(project_id)
      @project = project_id
      # Renders the project detail page content into a frame
      render "projects/show"
    else
      head :not_found
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_panel/blog_posts_helper.rb
module AdminPanel::BlogPostsHelper
end

app/helpers/admin_panel/tags_helper.rb
module AdminPanel::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(filter_html: true, hard_wrap: true)
    markdown = Redcarpet::Markdown.new(renderer, extensions = { autolink: true, tables: true, fenced_code_blocks: true })
    markdown.render(text).html_safe
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/about/index.html.erb
<turbo-frame id="content">
  <meta name="description" content="This is the about page for Johan Oh's personal website. It includes details about what frameworks and technology the website uses">
  
  <h1>About This Website</h1>

  <p>
    This is my personal website—built to be <strong>simple, fast, and fully under my control</strong>.
    No bloated frameworks, no unnecessary JavaScript—just clean HTML, CSS, Ruby on Rails, and Turbo Hotwire.
    Checkout the website that inspired the CSS <a href="https://bettermotherfuckingwebsite.com/" target="_blank">here</a>.
    Self-hosted on a Debian VM in my homelab. You can checkout a deeper dive on the projects page.
  </p>
</turbo-frame>

app/views/blog/index.html.erb
<%= turbo_frame_tag "content" do %>
  <meta name="description" content="This is the main blog listing page for Johan Oh's personal website.  It contains a list of blog posts">
  <h1>Blog</h1>

  <% @blog_posts.each do |post| %>
    <article>
      <h2>
        <%= link_to post.title, blog_path(post.slug), class: "blog-title" %>
      </h2>
      <p>Published At <%= post.published_at.strftime("%B %d, %Y") %></p>
      
      <% if post.tags.any? %>
        <p>Tags: 
          <% post.tags.each do |tag| %>
            <b> <%= tag.name %> </b>
          <% end %>
        </p>
      <% end %>
    </article>
  <% end %>


<% end %>

app/views/blog/show.html.erb
<%= turbo_frame_tag "content" do %>
<div class="project-template">
    <%= link_to "Back", :back, class: "back-button top" %>
    <%= link_to "Back to Blog", blog_index_path, class: "back-button top" %>
    <h1 class="blog-title-page"><%= @blog_post.title %></h1>
    <p><%= @blog_post.published_at.strftime("%B %d, %Y") %></p>

    <% if @blog_post.tags.any? %>
    <p>Tags:
        <% @blog_post.tags.each do |tag| %>
        <b> <%= tag.name %> </b>
        <% end %>
    </p>
    <% end %>
    <div class="project-content">
        <div>
            <%= markdown(@blog_post.content) %>
        </div>
    </div>
</div>

<% end %>

app/views/contact/_error.html.erb
<turbo-stream action="update" target="contact_form_status">
  <template>
    <p class="error"><%= local_assigns[:message] || "Something went wrong. Please try again later." %></p>
  </template>
</turbo-stream>

app/views/contact/_success.html.erb
<turbo-stream action="update" target="contact_form_status">
  <template>
    <p class="success">Your message has been sent successfully! I will strive to get back to you as soon as possible.</p>
  </template>
</turbo-stream>

app/views/contact/index.html.erb
<turbo-frame id="content">
  <div data-controller="contact">
    <h1 class="contact-container">Contact Me</h1>
    <div class="contact-container">
      <%= form_with url: "/contact", method: :post, data: { turbo_frame: "contact_form", action: "turbo:submit-end->contact#handleSubmitEnd" }, class: "contact-form" do |f| %>
        <div class="form-group">
          <label for="name">Name</label>
          <%= f.text_field :name, required: true %>
        </div>

        <div class="form-group">
          <label for="email">Email</label>
          <%= f.email_field :email, required: true %>
        </div>

        <div class="form-group">
          <label for="message">Message</label>
          <%= f.text_area :message, rows: 5, required: true %>
        </div>

        <button type="submit" class="btn">Send</button>
      <% end %>

      <!-- This is where the error message will appear -->
    </div>
    <div id="contact_form_status" class="contact-container" data-contact-target="status"></div>
  </div>
</turbo-frame>

app/views/home/index.html.erb
<turbo-frame id="content">
    <meta name="description" content="This is the main page for Johan Oh's personal website, and includes information about who he is and what he does">
    <h1>Johan Oh</h1>
    <p><strong>Software Developer | Torontonian</strong></p>

    <section class="section">
        <h2>About Me</h2>
        <p>Welcome to my personal website. I'm a self-taught software developer by trade, with 7 years of experience in the Fintech space. Outside of work, I’m usually wandering the city, tinkering with my homelab, getting lost in a book, or adding yet another unfinished project to my list.</p>
        <p>Born and raised in Toronto—aside from a few years in Sweden for high school—I love this city, for better or worse. Whether it's discovering a new coffee shop, catching a Leafs game, or cycling along the waterfront.</p>
        <p>Most weekends, you’ll find me on my bike, weaving through the city, hitting High Park, the Don Valley trails, or heading beyond to chase new scenic routes—while, of course, dodging the inevitable cars parked in bike lanes.</p>
        <p>
            Even though Toronto is home, I spent my high school years in Sweden—one of the perks of being a dual citizen. I try to keep up with my heritage and language as much as possible, mostly by watching Swedish television and news. 
            The difficult part comes to when to decide who to cheer for during international hockey games!
        </p>
    </section>
</turbo-frame>

app/views/projects/_project2.html.erb
<turbo-frame id="content">
    <meta name="description" content="Johan Oh's personal website project page. Learn about the motivation behind the project and the technologies used to build it.  Built with Ruby on Rails and Hotwire">

    <h1 class="blog-title-page">Personal Website Project</h1>

    <p>
        This page dives into the motivation behind my personal website, the technologies I used to build it, and some of the lessons I learned along the way. It’s a mix of a learning exercise and a passion project.
    </p>
    <section class="project-section">
        <h2>Motivation</h2>
        <p>
            I started this project between jobs in January 2025. The motivation behind creating this personal website was to build a space that I fully control,
            where I can showcase my work, interests, and the technology that powers my projects. This project is mostly a learning exercise in
            building and deploying a website from start to finish — from website design to infrastructure.
        </p>
        <p>
            I chose <strong><a href="https://rubyonrails.org/" target="_blank">Ruby on Rails</a></strong> for the backend based on my experience maintaining a large Rails platform at my previous job.
            Before Rails, I came from the Django world, but the two frameworks were similar enough that picking up Rails was relatively easy. That being said, I joined the project when
            it had already matured into a gnarly enterprise app (as they often do), which left me with a slightly sour taste for Rails. My manager, a Rails veteran, insisted that my frustrations stemmed from the project’s unorthodox structure
            not Rails itself. So, I decided to start fresh with a new Ruby on Rails project,
            hoping to redeem my admittedly poor introduction to the framework.
        </p>
        <p>
            I was also motivated to use <strong><a href="https://turbo.hotwired.dev/" target="_blank">Turbo (Hotwire + Stimulus)</a></strong> due to my interest in <strong><a href="https://htmx.org/" , target="_blank">HTMX</a></strong>, which shares a similar approach to Turbo's philosophy.
            Like HTMX, Turbo extends HTML to reduce the need for JavaScript and allows websites to be more interactive with minimal client-side code.
            Turbo integrates seamlessly with Rails, while HTMX is framework-agnostic.
            While both technologies enable the creation of dynamic, real-time user interfaces, they achieve this with different mechanisms: Turbo handles page updates via Turbo Streams,
            while Stimulus focuses on managing simple client-side interactions like toggling accordions.
            By using Turbo, the website behaves like a single-page application (SPA), but instead of relying on a heavy JavaScript framework, it uses lightweight Turbo Streams to update parts of the DOM without a full page refresh.
        </p>

        <p>
            I personally have reservations about using React for everything on the frontend (or, heaven forbid, the backend).
            React is powerful and absolutely has its place, but it can be overkill for simple CRUD-based applications that don’t require the level of interactivity that React is built to handle.
            For platforms like this one, where the main focus is displaying and managing content, HTMX and Turbo Hotwire offer a lighter, more streamlined solution.
            Even for larger enterprise applications, such as banking software, where state management is critical, there’s still value in considering alternatives to React.
            Sometimes, a simpler solution is the right one.
            As they say in the world of web development, <a href="https://www.erikheemskerk.nl/htmx-simplicity/" target="_blank">"Simplicity in the Age of Complicated Solutions"</a>.
        </p>
        <%
=begin%>
        Todo add reference to homelab post when completed
        <%
=end%>
        <p>
            One of my main hobbies is building and maintaining my homelab. I wanted to host this website on my own infrastructure,
            including automated deployment and backup systems. It has been a very informative experience in understanding how
            GitHub Actions and runners work, as well as a deeper dive into the cron side of things.
        </p>
    </section>

    <section class="project-section">
        <h2>Technologies Used</h2>
        <p>
            Here’s a quick rundown of the tools and frameworks that power the site:
        </p>

        <ul>
            <li><strong>Ruby on Rails</strong>: The foundation of the website. Rails is great for quickly building full-stack web apps and powers the server-side logic, models, and views.</li>
            <li><strong>Hotwire (Turbo + Stimulus)</strong>: Turbo handles partial page updates and real-time interactions via Turbo Streams, while Stimulus manages client-side interactions like toggling accordions. Together, they replace most JavaScript with lightweight HTML updates.</li>
            <li><strong>SQLite</strong>: A simple, efficient database perfect for a personal site. It's lightweight, integrates easily with Rails, and doesn’t require complex database management.</li>
            <li><strong>Custom Minimalist CSS</strong>: The design follows a minimalist approach with a focus on readability, speed, and clean typography. There are no heavy CSS frameworks — just the essentials to keep the site fast. Inspiration taken from <a href="https://bettermotherfuckingwebsite.com/" target="_blank">here</a>.</li>
            <li><strong>Markdown for Blog Posts</strong>: The blog posts are written in Markdown and stored in the database. They are rendered as HTML before being displayed on the site, providing a fast, flexible way to manage content.</li>
        </ul>
    </section>
    <section class="project-section">
        <h2>Wrapping Up</h2>
        <p>
            Building this website has been equal parts frustrating and rewarding. It’s reminded me why I love tinkering with code: there’s nothing quite like taking an idea from a rough sketch to a working product.
            I got to dust off my Rails skills, dive deeper into Turbo’s magic, and finally set up a self-hosted deployment pipeline.
        </p>
        <p>
            More than anything, this project solidified my belief that <em>simplicity matters</em>. You don’t always need React, Kubernetes, or a 10-microservice architecture for a personal blog.
            Sometimes a Rails app with SQLite, a sprinkle of Turbo, and a DIY Markdown system is more than enough. (Plus, it’s way more fun to host it yourself.)
        </p>
        <p>
            If you’re working on a similar project or just want to chat about Rails, Turbo, or homelab setups, 
            feel free to reach out via the contact page. I’d love to hear from you!
        </p>
    </section>

    <section class="project-section">
      <h3>Update 2025-02-22</h3>
          <p>
            Added dark mode! very simple, just needed to updated the CSS and a small JavaScript function, and now the website can automatically detect the system preferences, or you can toggle your preference at the bottom left.
          </p> 
    </section>
</turbo-frame>

app/views/projects/index.html.erb
<turbo-frame id="content">
    <h1>Projects</h1>

    <div class="projects">
        <% @projects.each do |project| %>
        <div class="project">
            <!-- Link to each project -->
            <%= link_to project.name, project_path(project.id), data: { turbo_frame: "content" } %>
        </div>
        <% end %>
    </div>
</turbo-frame>

app/views/projects/show.html.erb
<turbo-frame id="content">
    <div class="project-template">
        <%= link_to "Back", projects_path, class: "back-button top" %>
        <div class="project-content">
            <%= render "projects/#{@project}" %>
        </div>
    </div>

</turbo-frame>

app/views/projects/temp_project1.html.erb
<turbo-frame id="content">
    <div class="project-content">
        <h3>Introduction</h3>
        <p>
            This was a passion project during the Covid-19 pandemic.
            Stuck at home and with very little to do I discroved the world of homelabs.
            My introduction to it was the operating system Unraid. In November 2020 I bought my first set of hard drives I believe 3 4 TB drives, one to act as a parity drive, and the other two as regular drives, threw them into an old computer case, with running on an old AMD Ryzen 5 1600x CPU and 16 GB of RAM.
            Over the years I have added and tinkered with it, and now the Unraid server has a total of 114 TB of storage, and runs many docker containers and the VM that powers this website.
            Beside (or ontop, as the systems have been transfered to a server rack) is a Proxmox server with an Epyc CPU and 256 GB of RAM, and an Nvidia 3090 for running LLM's at home, 2 rasberry pis, one running <a href="https://pi-hole.net/" target="_blank">Pihole</a>, a DNS sink, DCHP server, and DNS server, and the other running Traefik as an entrypint into the network and providing SSL certificates.
            An older Intel Mac Mini that I use for experimemting with accessing iMessage with my Android phone, a 1U game server system that runs Ubuntu, but I will likely move it over to proxmox.

            why did I do this? To teach myself networking, working with metal, and de-Googling my life (including moving to a security concious Android fork called <a href="https://grapheneos.org/" target="_blank">GrapheneOS</a> )


        </p>

        <h3>Services</h3>

        <h4>Unraid Server</h4>
        <p>
            This is the core of the homelab. It acts as the main storage server as well as run many of the docker container services, such as CouchDB for syncing my Obsidian instances across devices. It has a total sotrage of 114 TB. It has the following hardware:
        </p>
        <ul>
            <li>Intel® Core™ i9-7960X CPU @ 2.80GHz (16 cores/32 threads)</li>
            <li>64 GB DDR4 RAM</li>
            <li>Nvidia P400 GPU (used for transcoding media files since the i9 does not have quicksync)</li>
            <li>Generic Mellonox 10GB Fiber Network Interface</li>
            <li>4x1TB SSD's in ZFS Raid 1 pool</li>
            <li>2X2TB NVME in RAID 0 (don't judge, sometimes I need fast storage)</li>
            <li>16 HDD of various capacities, the largest being 14TB, with two of them acting as parity drives</li>
        </ul>

        <h4>Proxmox Server</h4>

        <p>
            This is my main VM server. It has an AMD Eypc CPU and a crap ton of ram, as well as SSD storage. I use it for running VM's, such as Postgres databases, various flavours of linux. It is mostly a testbed that I use for testing "cloud" compute at home.
        </p>

        <h4>Rasberry Pi 1 (Pihole)</h4>
        <p>
            Like anyone who uses the internet extensively I have a strong aversion to advertisements and being tracked. The Pihole provides a DNS level ad and tracker blocking service. It is a godsend, and makes the internet usable.


        </p>
    </div>
</turbo-frame>